function result=f1(t,X,Y,alpha,nu)
Nx=length(X); Ny=length(Y);
result=zeros(Nx,Ny);
Xmesh=kron(ones(Ny,1),X);
Ymesh=kron(ones(1,Nx),Y(:));

result=(2/gamma(3-alpha)*power(t,2-alpha)+gamma(1+alpha))*(sin(Xmesh).^2).*sin(2*Ymesh)...
    +power(t^2+t^alpha+1,2)*(sin(Xmesh).^2).*sin(2*Xmesh).*(sin(2*Ymesh).^2)...
    -2*power(t^2+t^alpha+1,2)*(sin(Xmesh).^2).*sin(2*Xmesh).*(sin(Ymesh).^2).*cos(2*Ymesh)...
    -nu*(2*(t^2+t^alpha+1)*cos(2*Xmesh)-4*(t^2+t^alpha+1)*(sin(Xmesh).^2)).*sin(2*Ymesh)...
    -(t^2+t^alpha+1)^2*sin(Xmesh).*sin(Ymesh);

end